spring.application.name=Assignment_Trainee_Management_19_03_2026

server.port=8087

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Karan@1709
spring.datasource.url=jdbc:mysql://localhost:3306/sbdatabase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true